name: CI workflow

on:
  pull_request:
  push:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  unit-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      shell: pwsh
      # https://github.com/ScoopInstaller/Install#for-admin
      run: |
        iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
        scoop install mingw
    - name: UnitTest
      run: make test
